### ISSUE TITLE
Extra line in Paragraph

### ISSUE THREAD

**Issue by DhruvaSambrani** [kdheepak/TerminalUserInterfaces.jl#11]
The bottom border of a Paragraph is overwritten by the last line. It seems like a simple off by 1 error in displaying the Paragraph, or in the `inner` of a Block.

See below for reference.

![image](https://user-images.githubusercontent.com/44899822/129313841-af01210b-6211-4f67-b33d-b20e1bd7aa98.png)

Run on julia 1.6.2, error reproduceable on release and master of TUI.jl

**Comment by kdheepak** [comment]
Thanks for reporting. I’ll take a look at this over the weekend.

**Comment by DhruvaSambrani** [comment]
Note that this only happens when the height of the Rect passed while drawing the Paragraph is > the height of the terminal

**Comment by kdheepak** [comment]
This is fixed in a recent release:

![](https://github.com/kdheepak/TerminalUserInterfaces.jl/assets/1813121/a167f0b2-3341-4ab2-9d0c-2bda942ab616)
