### ISSUE TITLE
Initialization fails on windows machine

### ISSUE THREAD

**Issue by YongHee-Kim** [kdheepak/TerminalUserInterfaces.jl#13]
```julia
julia> using TerminalUserInterfaces
ERROR: InitError: MethodError: no method matching tcgetattr(::Base.Libc.WindowsRawSocket, ::TERMIOS.termios)
Closest candidates are:
  tcgetattr(::Base.LibuvStream, ::Any) at C:\Users\Maste\.julia\dev\TERMIOS\src\TERMIOS.jl:612 
  tcgetattr(::Int64, ::Any) at C:\Users\Maste\.julia\dev\TERMIOS\src\TERMIOS.jl:613
  tcgetattr(::RawFD, ::TERMIOS.termios) at C:\Users\Maste\.julia\dev\TERMIOS\src\TERMIOS.jl:608
Stacktrace:
  [1] tcgetattr(s::Base.TTY, term::TERMIOS.termios)
    @ TERMIOS C:\Users\Maste\.julia\dev\TERMIOS\src\TERMIOS.jl:612
  [2] backup_termios()
    @ TerminalUserInterfaces C:\Users\Maste\.julia\dev\TerminalUserInterfaces\src\utils.jl:198
......
```
https://github.com/kdheepak/TerminalUserInterfaces.jl/blob/6061a012c8f94577c48961f171d2a0a27e44573d/src/utils.jl#L198

both `stdin` and `stdout` were not IO type. 
```julia
julia> stdin
Base.TTY(Base.Libc.WindowsRawSocket(0x0000000000000254) open, 0 bytes waiting)

julia> stdout
Base.TTY(Base.Libc.WindowsRawSocket(0x0000000000000228) open, 0 bytes waiting) 
```

I'm on Julia 1.7.1 and here is my full `versioninfo()`
```
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD Ryzen 7 5800X 8-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, znver3)
```

**Comment by kdheepak** [comment]
Something must have changed in Julia for Windows. I don’t have a Windows machine to test though. If you can, can you share the output of `@show stdin stdout` on Windows, with Julia v1.5 or Julia v1.6?

**Comment by YongHee-Kim** [comment]
![image](https://user-images.githubusercontent.com/7087745/155993573-9cea4ff8-7ad8-4a4d-9470-1120d2322246.png)
It's same for 1.5 and 1.6, but I vaguely remmber that `stdin` `stdot` was subtype of `IO` too

```julia
julia> supertype(Base.TTY)
Base.LibuvStream

julia> supertype(Base.Libc.WindowsRawSocket)
Any
``

**Comment by kdheepak** [comment]
I made a new release v0.3.0

https://github.com/kdheepak/TerminalUserInterfaces.jl/releases/tag/v0.3.0

This uses Crossterm.jl instead of Termios.jl, which should work on Windows, Mac and Linux.
