### ISSUE TITLE
ioctl failed: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by remy-luisant** [kdheepak/TerminalUserInterfaces.jl#7]
Hi,

Here's the error that I get, pretty much right out of the gate.

```
julia> using TerminalUserInterfaces
julia> const TUI = TerminalUserInterfaces
TerminalUserInterfaces
julia> TUI.terminal_size()
ERROR: ioctl failed: Inappropriate ioctl for device
Stacktrace:
 [1] ioctl(fd::RawFD, parameter::Int64)
   @ TerminalUserInterfaces.IOCTL ~/.julia/packages/TerminalUserInterfaces/ha2Cg/src/ioctl.jl:123
 [2] ioctl
   @ ~/.julia/packages/TerminalUserInterfaces/ha2Cg/src/ioctl.jl:126 [inlined]
 [3] terminal_size(io::Base.TTY)
   @ TerminalUserInterfaces ~/.julia/packages/TerminalUserInterfaces/ha2Cg/src/utils.jl:9
 [4] terminal_size()
   @ TerminalUserInterfaces ~/.julia/packages/TerminalUserInterfaces/ha2Cg/src/utils.jl:13
 [5] top-level scope
   @ REPL[3]:1
```

```
julia> versioninfo()
Julia Version 1.6.1
Commit 6aaedecc44* (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.1.0 (ORCJIT, skylake)
```

```
(@v1.6) pkg> status TerminalUserInterfaces
      Status `~/.julia/environments/v1.6/Project.toml`
  [408767e4] TerminalUserInterfaces v0.2.0
```

I'm on Arch Linux. This happens both in the text console and in a terminal emulator running under X.

**Comment by remy-luisant** [comment]
Possibly related to #3.

**Comment by kdheepak** [comment]
Can you try the latest `master` branch and see if you are still experiencing this issue?

**Comment by remy-luisant** [comment]
Yup, this is fixed on master.

**Comment by kdheepak** [comment]
I should make a new release then. I'll do that and then close this issue.

**Comment by remy-luisant** [comment]
I had issues with the progress bar example, with only the percentage displaying.

This might be my computer, but I don't believe so at this point.

I am looking into it, but it might be an idea to either wait a bit with a release or to be ready for a new bugfix release soon.

**Comment by kdheepak** [comment]
Can you share a screenshot of what is going on?

**Comment by remy-luisant** [comment]
Sure. I'll make a new issue tomorrow, with a video recording.

**Comment by kdheepak** [comment]
I believe this issue should be resolved with https://github.com/kdheepak/TerminalUserInterfaces.jl/releases/tag/v0.3.0.
