### ISSUE TITLE
Progress bars not visible.

### ISSUE THREAD

**Issue by remy-luisant** [kdheepak/TerminalUserInterfaces.jl#8]
I am using the master branch of TUI, on Arch Linux, Julia 1.6.1.

Only the percentage is visible, which I don't believe was intended.

Recording [here](https://luisant.ca/progress_bar.mp4).

**Comment by kdheepak** [comment]
The progress bar widget hard codes the background to be black: https://github.com/kdheepak/TerminalUserInterfaces.jl/blob/master/src/widgets/progressbar.jl#L17

I think that’s what is going on here.

**Comment by remy-luisant** [comment]
I can confirm that changing my terminal background made a bar appear.

A proposed fix: The bar could have a black color, being replaced by a white as the progress goes on, with the text being bright white if the bar is not behind it and becoming black if the bar starts overlapping it. This should be visible as progress on any combination of terminal settings.

**Comment by kdheepak** [comment]
Can you try the most recent commit? 

https://github.com/kdheepak/TerminalUserInterfaces.jl/blob/e1946a7e106dd4563e57e04a878c04909d96861a/src/widgets/progressbar.jl#L17

**Comment by kdheepak** [comment]
I seem to have changed it from using `:white` and `:black` to hardcoded values a while ago, but I can't remember why:

https://github.com/kdheepak/TerminalUserInterfaces.jl/commit/3e095ff933ddbfb70a6055e2b83b51447c587506#diff-d4c1b4784a623b4120fc107f6e6e18d0d7fe3149ed1494add012bce57463fa67

Anyway, let me know whether it works. I think this will use what `:white` and `:black` have been defined as by your terminal theme.

**Comment by remy-luisant** [comment]
No change. My temporary purple background gets replaced by black as progress is made. I don't believe this was the intent behind the code. I would have expected the entire bar to be drawn, in white and black, not partially in my background purple.

Recording [here](https://luisant.ca/progress_bar_2.mp4)

**Comment by kdheepak** [comment]
Can you run `using Crayons; Crayons.test_system_colors()`?

<img width="380" alt="Screen Shot 2021-06-01 at 1 13 51 PM" src="https://user-images.githubusercontent.com/1813121/120378104-3fdce680-c2db-11eb-81ac-8f1d7f176793.png">

**Comment by kdheepak** [comment]
I've made a new change (see https://github.com/kdheepak/TerminalUserInterfaces.jl/commit/72c64dd074e7c833151e6607a00022e85ef5807f) where you can pass in the colors as a crayon to the ProgressBar struct. You can change the colors accordingly.

**Comment by remy-luisant** [comment]
Here you go.

![crayons](https://user-images.githubusercontent.com/26334962/120378705-9b0adb00-c2d3-11eb-9df6-95cb661fc3a9.png)

**Comment by remy-luisant** [comment]
I used a red and green crayon for the bar. This is sufficient to let me make progress, but it was not an expected result.

I was expecting a red bar, slowly filling up with green as progress is being made. Instead, I got a black bar filling up with green. The text started as white, and turned red when the green bar made progress through it. I would suspect inv() not doing the proper job on the crayon and picking the default colors instead.

Would you like a video of what I currently have?

Either way, this solves my problem sufficiently. Thank you.

**Comment by remy-luisant** [comment]
I do believe inv() fails on Crayons, or at least isn't the intended behavior:
```
julia> a = Crayon(; foreground=:white, background=:black)
\e[97;40m
julia> inv(a).bg
Crayons.ANSIColor(0x09, 0x00, 0x00, Crayons.COLORS_16, true)
julia> inv(a).fg
Crayons.ANSIColor(0x09, 0x00, 0x00, Crayons.COLORS_16, true)
julia> a.fg
Crayons.ANSIColor(0x43, 0x00, 0x00, Crayons.COLORS_16, true)
julia> a.bg
Crayons.ANSIColor(0x00, 0x00, 0x00, Crayons.COLORS_16, true)
```

**Comment by kdheepak** [comment]
I've added a new ProgressBar that allows for more customization. That should help with this issue.
